name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy
        pip install TextBlob
        pip install pandas
    - name: Run twi_api
      env:
          apiKey: ${{ secrets.apiKey }}
          apiSecret:  ${{ secrets.apiSecret }} 
          accessToken: ${{ secrets.accessToken }}
          accessTokenSecret: ${{ secrets.accessTokenSecret }} 
      run: |
        cd project2/test
        python twi_api.py
